import { Level, Module } from '../types/database';

export const INITIAL_LEVELS: Level[] = [
  {
    id: 'lvl-a1-1',
    code: 'a1-1',
    title: 'A1.1 — Boshlang‘ich bosqich (Mutlaq yangi boshlovchilar)',
    cefrLevel: 'A1.1',
    descriptionUz: 'Nemis tilini 0 dan boshlovchilar uchun: tanishuv, alifbo va talaffuz, sonlar, soat, oila, xaridlar va asosiy kundalik muloqot.',
    targetAudience: 'Nemis tilida mutlaqo bilimga ega bo‘lmagan o‘quvchilar',
    estimatedHours: 60,
    orderIndex: 1,
    isActive: true,
  },
  {
    id: 'lvl-a1-2',
    code: 'a1-2',
    title: 'A1.2 — Boshlang‘ich davomi (Kundalik muloqot va o‘tgan zamon)',
    cefrLevel: 'A1.2',
    descriptionUz: 'Kundalik faoliyat, ish, sog‘liq, shahar va transport, ajraladigan fe‘llar, modal fe‘llar, Dativ va Perfekt (o‘tgan zamon).',
    targetAudience: 'A1.1 bosqichini o‘zlashtirgan o‘quvchilar',
    estimatedHours: 65,
    orderIndex: 2,
    isActive: true,
  },
  {
    id: 'lvl-a2-1',
    code: 'a2-1',
    title: 'A2.1 — O‘rta-quyi bosqich (Tez orada)',
    cefrLevel: 'A2.1',
    descriptionUz: 'Tez orada — A1 bosqichi to‘liq yakunlangach taqdim etiladi.',
    targetAudience: 'A1 sertifikatiga ega bo‘lgan o‘quvchilar',
    estimatedHours: 70,
    orderIndex: 3,
    isActive: false,
    isComingSoon: true,
  },
  {
    id: 'lvl-a2-2',
    code: 'a2-2',
    title: 'A2.2 — O‘rta-quyi yakuniy (Tez orada)',
    cefrLevel: 'A2.2',
    descriptionUz: 'Tez orada — A1 bosqichi to‘liq yakunlangach taqdim etiladi.',
    targetAudience: 'A2.1 o‘quvchilari',
    estimatedHours: 75,
    orderIndex: 4,
    isActive: false,
    isComingSoon: true,
  },
  {
    id: 'lvl-b1-1',
    code: 'b1-1',
    title: 'B1.1 — Mustaqil til egasi (Tez orada)',
    cefrLevel: 'B1.1',
    descriptionUz: 'Tez orada — B1 xalqaro sertifikatiga tayyorgarlik kursi.',
    targetAudience: 'A2 darajasini tugatgan talabalar',
    estimatedHours: 85,
    orderIndex: 5,
    isActive: false,
    isComingSoon: true,
  },
  {
    id: 'lvl-b1-2',
    code: 'b1-2',
    title: 'B1.2 — Mustaqil muloqot va sertifikat (Tez orada)',
    cefrLevel: 'B1.2',
    descriptionUz: 'Tez orada — Goethe/telc B1 imtihoniga tayyorgarlik.',
    targetAudience: 'B1 imtihoni topshiruvchilar',
    estimatedHours: 90,
    orderIndex: 6,
    isActive: false,
    isComingSoon: true,
  },
];

export const INITIAL_MODULES: Module[] = [
  // ==========================================
  // --- MENSCHEN A1.1 (MODUL 1 - 4) ---
  // ==========================================
  {
    id: 'mod-1',
    levelId: 'lvl-a1-1',
    levelCode: 'a1-1',
    titleDe: 'Modul 1: Erstes Kennenlernen',
    titleUz: '1-Modul: Dastlabki tanishuv va muloqot',
    descriptionUz: 'Salomlashish, ism va kelib chiqish, kasblar va oila a‘zolari (Lektion 1, 2, 3).',
    orderIndex: 1,
    reviewSummaryUz: '1-Modulda siz nemischa salomlashuv, o‘zingizni tanishtirish, kasblar, oila a‘zolari, "sein" va "haben" fe‘llari tuslanishini o‘rgandingiz.',
  },
  {
    id: 'mod-2',
    levelId: 'lvl-a1-1',
    levelCode: 'a1-1',
    titleDe: 'Modul 2: Gegenstände und Einkaufen',
    titleUz: '2-Modul: Buyumlar va xarid qilish',
    descriptionUz: 'Mebellar, buyumlar, ranglar, aniq va noaniq artikllar (der/die/das, ein/eine), inkor (kein/nicht) va Akkusativ (Lektion 4, 5, 6).',
    orderIndex: 2,
    reviewSummaryUz: '2-Modulda buyumlar nomlari, nemischa artikllar tizimi, ko‘plik shakllari va Akkusativ (den / einen / keinen) mustahkamlandi.',
  },
  {
    id: 'mod-3',
    levelId: 'lvl-a1-1',
    levelCode: 'a1-1',
    titleDe: 'Modul 3: Essen, Trinken und Freizeit',
    titleUz: '3-Modul: Yegulik, ichimlik va bo‘sh vaqt',
    descriptionUz: 'Oziq-ovqat mahsulotlari, supermarketda xarid, narxlar va xobbi bilan shug‘ullanish (Lektion 7, 8, 9).',
    orderIndex: 3,
    reviewSummaryUz: '3-Modulda oziq-ovqatlar, xushmuomala buyurtma (Ich möchte...), narx so‘rash va sevimli mashg‘ulotlar haqida gapirish o‘zlashtirildi.',
  },
  {
    id: 'mod-4',
    levelId: 'lvl-a1-1',
    levelCode: 'a1-1',
    titleDe: 'Modul 4: Zeit, Alltag und Wohnen',
    titleUz: '4-Modul: Vaqt, kun tartibi va yashash joyi',
    descriptionUz: 'Soat vaqti (rasmiy/norasmiy), kun tartibi va ajraladigan fe‘llar, kvartira va xonalar (Lektion 10, 11, 12).',
    orderIndex: 4,
    reviewSummaryUz: '4-Modulda soat aytish, vaqt predloglari (um, am), ajraladigan fe‘llar (aufstehen, anfangen) va xonalar tasviri egallandi.',
  },

  // ==========================================
  // --- MENSCHEN A1.2 (MODUL 5 - 8) ---
  // ==========================================
  {
    id: 'mod-a1-2-1',
    levelId: 'lvl-a1-2',
    levelCode: 'a1-2',
    titleDe: 'Modul 5: Unterwegs und Orientierung',
    titleUz: '5-Modul: Shahar bo‘ylab va yo‘l topish',
    descriptionUz: 'Shaharda yo‘l so‘rash, jamoat transporti (mit + Dativ), chiptalar va mehmonxonada joylashish (Lektion 13, 14, 15).',
    orderIndex: 1,
    reviewSummaryUz: '5-Modulda yo‘nalish so‘rash, "mit dem Bus/Zug" (Dativ) qoidasi va mehmonxonada buyurtma berish o‘rganildi.',
  },
  {
    id: 'mod-a1-2-2',
    levelId: 'lvl-a1-2',
    levelCode: 'a1-2',
    titleDe: 'Modul 6: Gesundheit und Körper',
    titleUz: '6-Modul: Salomatlik va inson tanasi',
    descriptionUz: 'Tana a‘zolari, og‘riqlar (tut weh), shifokor qabuli, dorixona va maslahat berish (Imperativ va modal fe‘l sollen) (Lektion 16, 17, 18).',
    orderIndex: 2,
    reviewSummaryUz: '6-Modulda tana a‘zolari, "weh tun", shifokor retsepti va buyruq-maslahat shakllari egallandi.',
  },
  {
    id: 'mod-a1-2-3',
    levelId: 'lvl-a1-2',
    levelCode: 'a1-2',
    titleDe: 'Modul 7: Wohnen und Arbeitswelt',
    titleUz: '7-Modul: Uy jihozlash va ish faoliyati',
    descriptionUz: 'Mebellar joylashuvi (Wo? + Dativ), yo‘nalish (Wohin? + Akkusativ), kasbiy faoliyat va modal fe‘llar (können, müssen, dürfen) (Lektion 19, 20, 21).',
    orderIndex: 3,
    reviewSummaryUz: '7-Modulda Wechselpräpositionen (an, auf, in, neben), mebel joylashtirish va kasbiy suhbatlar o‘rganildi.',
  },
  {
    id: 'mod-a1-2-4',
    levelId: 'lvl-a1-2',
    levelCode: 'a1-2',
    titleDe: 'Modul 8: Freizeit, Pläne und Vergangenheit',
    titleUz: '8-Modul: Rejalar, bayramlar va o‘tgan zamon',
    descriptionUz: 'Kiyimlar va ob-havo, taklifnomalar va "weil" (chunki) bog‘lovchisi, o‘tgan zamon (Perfekt mit haben und sein) (Lektion 22, 23, 24).',
    orderIndex: 4,
    reviewSummaryUz: '8-Modulda "weil" ergash gapi, kiyimlar va nemis tilidagi asosiy o‘tgan zamon — Perfekt to‘liq o‘zlashtirildi.',
  }
];
