import { CertificateTest } from '../types/certificate';

export const INITIAL_CERTIFICATE_TESTS: CertificateTest[] = [
  {
    id: 'cert-test-a1-1',
    levelCode: 'a1-1',
    titleDe: 'For Great Nation A1.1 Assessment',
    titleUz: 'A1.1 Nemis Tili Baholash Imtihoni',
    descriptionUz: 'A1.1 darajasidagi barcha mavzular (tanishuv, oila, xaridlar, taomlar va kun tartibi) bo‘yicha o‘qish (Lesen) va tinglab tushunish (Hören) ko‘nikmalarini tekshiruvchi standartlashtirilgan test.',
    durationMinutes: 30,
    passingPercentage: 60,
    isPublished: true,
    totalPoints: 40,
    totalQuestions: 10,
    sections: [
      {
        id: 'sec-a1-1-lesen',
        testId: 'cert-test-a1-1',
        skill: 'reading',
        titleDe: 'Teil 1: Lesen (O‘qish va Tushunish)',
        titleUz: '1-Bo‘lim: O‘qib tushunish',
        instructionsUz: 'Har bir matn yoki e‘lonni diqqat bilan o‘qing va berilgan savollarga to‘g‘ri javobni tanlang.',
        orderIndex: 1,
        questions: [
          {
            id: 'q-a1-1-r1',
            sectionId: 'sec-a1-1-lesen',
            orderIndex: 1,
            type: 'multiple_choice',
            promptDe: 'Woher kommt Herr Weber und wo wohnt er?',
            promptUz: 'Matn bo‘yicha: Janob Veber qayerdan kelgan va hozir qayerda yashaydi?',
            passageDe: 'Hallo! Mein Name ist Thomas Weber. Ich komme aus Österreich, aus Wien. Aber jetzt wohne ich seit zwei Jahren in Berlin und arbeite dort als Informatiker. Meine Muttersprache ist Deutsch und ich lerne auch Englisch.',
            options: [
              { id: 'opt-1', textDe: 'Er kommt aus Deutschland und wohnt in Wien.', textUz: 'U Germaniyadan kelgan va Venada yashaydi.' },
              { id: 'opt-2', textDe: 'Er kommt aus Österreich und wohnt in Berlin.', textUz: 'U Avstriyadan kelgan va Berlinda yashaydi.' },
              { id: 'opt-3', textDe: 'Er kommt aus Berlin und wohnt in Österreich.', textUz: 'U Berlindan kelgan va Avstriyada yashaydi.' },
              { id: 'opt-4', textDe: 'Er wohnt seit zehn Jahren in Wien.', textUz: 'U o‘n yildan beri Venada yashaydi.' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Matnda aniq aytilgan: "Ich komme aus Österreich... Aber jetzt wohne ich... in Berlin." Demak, u Avstriyadan kelgan va hozir Berlinda yashaydi.',
          },
          {
            id: 'q-a1-1-r2',
            sectionId: 'sec-a1-1-lesen',
            orderIndex: 2,
            type: 'true_false',
            promptDe: 'Richtig oder Falsch: Der Supermarkt ist am Sonntag geöffnet.',
            promptUz: 'To‘g‘ri yoki Noto‘g‘ri: Supermarket yakshanba kuni ochiqmi?',
            passageDe: 'SUPERMARKT FRISCH & GUT\nÖffnungszeiten:\nMontag bis Freitag: 08:00 – 20:00 Uhr\nSamstag: 08:00 – 18:00 Uhr\nSonntag und Feiertage: Geschlossen!',
            options: [
              { id: 'opt-r', textDe: 'Richtig (To‘g‘ri)', textUz: 'Supermarket yakshanba kuni ochiq' },
              { id: 'opt-f', textDe: 'Falsch (Noto‘g‘ri)', textUz: 'Supermarket yakshanba kuni yopiq' },
            ],
            correctAnswer: 'opt-f',
            points: 4,
            explanationUz: 'E‘londa "Sonntag und Feiertage: Geschlossen!" (Yakshanba va bayram kunlari: Yopiq!) deb yozilgan.',
          },
          {
            id: 'q-a1-1-r3',
            sectionId: 'sec-a1-1-lesen',
            orderIndex: 3,
            type: 'multiple_choice',
            promptDe: 'Was möchte Sarah im Restaurant bestellen?',
            promptUz: 'Sara restoranda nima buyurtma qilmoqchi?',
            passageDe: 'Guten Tag, Herr Ober! Ich nehme ein Mineralwasser ohne Kohlensäure und eine Gemüsesuppe. Mein Freund möchte lieber einen Apfelsaft und eine Pizza mit Käse.',
            options: [
              { id: 'opt-1', textDe: 'Apfelsaft und Pizza', textUz: 'Olma sharbati va pitsa' },
              { id: 'opt-2', textDe: 'Mineralwasser und Gemüsesuppe', textUz: 'Gazsiz mineral suv va sabzavotli sho‘rva' },
              { id: 'opt-3', textDe: 'Kaffee und Kuchen', textUz: 'Qahva va pirog' },
              { id: 'opt-4', textDe: 'Nur ein Glas Cola', textUz: 'Faqat bir stakan kola' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Sara aytmoqda: "Ich nehme ein Mineralwasser... und eine Gemüsesuppe." (Apfelsaft va pizzani uning do‘sti buyurtma qilmoqda).',
          },
          {
            id: 'q-a1-1-r4',
            sectionId: 'sec-a1-1-lesen',
            orderIndex: 4,
            type: 'multiple_choice',
            promptDe: 'Wann treffen sich Maria und Anna?',
            promptUz: 'Mariya va Anna soat nechada uchrashishadi?',
            passageDe: 'Liebe Anna, ich habe am Samstag Zeit. Treffen wir uns um 15:30 Uhr vor dem Kino? Danach können wir ins Café gehen. Schreib mir bitte! Liebe Grüße, Maria.',
            options: [
              { id: 'opt-1', textDe: 'Um 14:00 Uhr im Café', textUz: 'Soat 14:00 da kafeda' },
              { id: 'opt-2', textDe: 'Um 15:30 Uhr vor dem Kino', textUz: 'Soat 15:30 da kinoteatr oldida' },
              { id: 'opt-3', textDe: 'Am Sonntag um 15:30 Uhr', textUz: 'Yakshanba kuni soat 15:30 da' },
              { id: 'opt-4', textDe: 'Um 18:00 Uhr zu Hause', textUz: 'Soat 18:00 da uyda' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'SMS xatida "Treffen wir uns um 15:30 Uhr vor dem Kino?" (Soat 15:30 da kinoteatr oldida uchrashamizmi?) deyilgan.',
          },
          {
            id: 'q-a1-1-r5',
            sectionId: 'sec-a1-1-lesen',
            orderIndex: 5,
            type: 'multiple_choice',
            promptDe: 'Was kostet das Fahrrad?',
            promptUz: 'Velosipedning narxi qancha?',
            passageDe: 'VERKAUFE DAMENFAHRRAD:\nSehr guter Zustand, 2 Jahre alt, blaue Farbe.\nNeupreis war 450 Euro. Jetzt nur 120 Euro Verhandlungsbasis!\nTelefon: 0176-55443322.',
            options: [
              { id: 'opt-1', textDe: '450 Euro', textUz: '450 yevro (yangi narxi)' },
              { id: 'opt-2', textDe: '120 Euro', textUz: '120 yevro (hozirgi sotuv narxi)' },
              { id: 'opt-3', textDe: '200 Euro', textUz: '200 yevro' },
              { id: 'opt-4', textDe: 'Kostenlos', textUz: 'Bepul' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'E‘londa: "Jetzt nur 120 Euro" (Hozir atigi 120 yevro) deb ko‘rsatilgan.',
          },
        ],
      },
      {
        id: 'sec-a1-1-hoeren',
        testId: 'cert-test-a1-1',
        skill: 'listening',
        titleDe: 'Teil 2: Hören (Tinglab Tushunish)',
        titleUz: '2-Bo‘lim: Tinglab tushunish',
        instructionsUz: 'Audioni diqqat bilan tinglang (istalgancha takrorlashingiz mumkin). Eshitilgan ma‘lumot asosida to‘g‘ri javobni belgilang.',
        orderIndex: 2,
        questions: [
          {
            id: 'q-a1-1-h1',
            sectionId: 'sec-a1-1-hoeren',
            orderIndex: 6,
            type: 'multiple_choice',
            promptDe: 'Auf welchem Gleis fährt der Zug nach München ab?',
            promptUz: 'Myunxenga boradigan poyezd nechanchi yo‘ldan (Gleis) jo‘naydi?',
            audioText: 'Achtung an Gleis 4: Der Intercity-Express nach München über Nürnberg, Abfahrt 14 Uhr 25, fährt heute abweichend von Gleis 7 ab. Ich wiederhole: Abfahrt von Gleis 7.',
            transcriptDe: 'Achtung an Gleis 4: Der Intercity-Express nach München über Nürnberg, Abfahrt 14 Uhr 25, fährt heute abweichend von Gleis 7 ab. Ich wiederhole: Abfahrt von Gleis 7.',
            options: [
              { id: 'opt-1', textDe: 'Gleis 4', textUz: '4-yo‘l' },
              { id: 'opt-2', textDe: 'Gleis 7', textUz: '7-yo‘l' },
              { id: 'opt-3', textDe: 'Gleis 14', textUz: '14-yo‘l' },
              { id: 'opt-4', textDe: 'Gleis 25', textUz: '25-yo‘l' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Vokzal xabarnomasida: "fährt heute abweichend von Gleis 7 ab" (bugun 7-yo‘ldan jo‘naydi) deb aniq ta‘kidlandi.',
          },
          {
            id: 'q-a1-1-h2',
            sectionId: 'sec-a1-1-hoeren',
            orderIndex: 7,
            type: 'multiple_choice',
            promptDe: 'Wie viel kostet der Pullover heute im Angebot?',
            promptUz: 'Chegirmada sviter bugun necha yevro turadi?',
            audioText: 'Guten Tag, liebe Kundinnen und Kunden. Heute in unserer Textilabteilung: Alle Pullover für Damen und Herren reduziert! Statt 50 Euro zahlen Sie heute nur 29 Euro. Greifen Sie zu!',
            transcriptDe: 'Guten Tag, liebe Kundinnen und Kunden. Heute in unserer Textilabteilung: Alle Pullover für Damen und Herren reduziert! Statt 50 Euro zahlen Sie heute nur 29 Euro. Greifen Sie zu!',
            options: [
              { id: 'opt-1', textDe: '50 Euro', textUz: '50 yevro' },
              { id: 'opt-2', textDe: '29 Euro', textUz: '29 yevro' },
              { id: 'opt-3', textDe: '19 Euro', textUz: '19 yevro' },
              { id: 'opt-4', textDe: '35 Euro', textUz: '35 yevro' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Audioda e‘lon qilinmoqda: "Statt 50 Euro zahlen Sie heute nur 29 Euro." (50 yevro o‘rniga bugun faqat 29 yevro to‘laysiz).',
          },
          {
            id: 'q-a1-1-h3',
            sectionId: 'sec-a1-1-hoeren',
            orderIndex: 8,
            type: 'true_false',
            promptDe: 'Richtig oder Falsch: Lukas ruft an, weil er heute Abend nicht kommen kann.',
            promptUz: 'To‘g‘ri yoki Noto‘g‘ri: Lukas bugun kechqurun kela olmasligi sababli qo‘ng‘iroq qilyaptimi?',
            audioText: 'Hallo Peter, hier ist Lukas. Du, es tut mir furchtbar leid, aber ich kann heute Abend leider nicht zu deiner Party kommen. Ich habe hohes Fieber und muss im Bett bleiben. Wir telefonieren morgen, ja? Tschüss.',
            transcriptDe: 'Hallo Peter, hier ist Lukas. Du, es tut mir furchtbar leid, aber ich kann heute Abend leider nicht zu deiner Party kommen. Ich habe hohes Fieber und muss im Bett bleiben. Wir telefonieren morgen, ja? Tschüss.',
            options: [
              { id: 'opt-r', textDe: 'Richtig (To‘g‘ri)', textUz: 'Lukas isitmasi chiqqani uchun ziyofatga kela olmaydi' },
              { id: 'opt-f', textDe: 'Falsch (Noto‘g‘ri)', textUz: 'Lukas vaqtida yetib kelishini aytmoqda' },
            ],
            correctAnswer: 'opt-r',
            points: 4,
            explanationUz: 'Lukas aytmoqda: "ich kann heute Abend leider nicht zu deiner Party kommen. Ich habe hohes Fieber." Demak, gap to‘g‘ri (Richtig).',
          },
          {
            id: 'q-a1-1-h4',
            sectionId: 'sec-a1-1-hoeren',
            orderIndex: 9,
            type: 'multiple_choice',
            promptDe: 'Wie ist die Telefonnummer von Frau Müller?',
            promptUz: 'Muller xonimning telefon raqami qaysi?',
            audioText: 'Guten Tag, hier spricht Müller von der Zahnarztpraxis Dr. Schmidt. Bitte rufen Sie uns zurück unter der Nummer: null, eins, sieben, zwei, sechs, vier, drei, fünf, acht. Danke auf Wiederhören.',
            transcriptDe: 'Guten Tag, hier spricht Müller von der Zahnarztpraxis Dr. Schmidt. Bitte rufen Sie uns zurück unter der Nummer: 0172 - 64 35 8. Danke auf Wiederhören.',
            options: [
              { id: 'opt-1', textDe: '0172 - 64 35 8', textUz: '0172 - 64 35 8' },
              { id: 'opt-2', textDe: '0171 - 64 35 8', textUz: '0171 - 64 35 8' },
              { id: 'opt-3', textDe: '0172 - 54 36 8', textUz: '0172 - 54 36 8' },
              { id: 'opt-4', textDe: '0173 - 64 35 9', textUz: '0173 - 64 35 9' },
            ],
            correctAnswer: 'opt-1',
            points: 4,
            explanationUz: 'Audiodagi nemischa raqamlar: null (0), eins (1), sieben (7), zwei (2), sechs (6), vier (4), drei (3), fünf (5), acht (8).',
          },
          {
            id: 'q-a1-1-h5',
            sectionId: 'sec-a1-1-hoeren',
            orderIndex: 10,
            type: 'multiple_choice',
            promptDe: 'Wie wird das Wetter morgen in Norddeutschland?',
            promptUz: 'Ertaga Germaniya shimolida ob-havo qanday bo‘ladi?',
            audioText: 'Und nun das Wetter für morgen, Donnerstag: Im Süden Deutschlands scheint meist die Sonne bei warmen 24 Grad. Im Norden dagegen ist es bewölkt und am Nachmittag gibt es leichten Regen bei nur 16 Grad.',
            transcriptDe: 'Und nun das Wetter für morgen, Donnerstag: Im Süden Deutschlands scheint meist die Sonne bei warmen 24 Grad. Im Norden dagegen ist es bewölkt und am Nachmittag gibt es leichten Regen bei nur 16 Grad.',
            options: [
              { id: 'opt-1', textDe: 'Sonnig und warm (24 Grad)', textUz: 'Quyoshli va iliq (24 daraja)' },
              { id: 'opt-2', textDe: 'Bewölkt mit leichtem Regen (16 Grad)', textUz: 'Bulutli va yengil yomg‘ir (16 daraja)' },
              { id: 'opt-3', textDe: 'Schneefall und kalt', textUz: 'Qor va sovuq' },
              { id: 'opt-4', textDe: 'Stürmisch mit Gewitter', textUz: 'Bo‘ron va chaqmoq' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Audioda shimol (im Norden) haqida aytildi: "Im Norden dagegen ist es bewölkt und am Nachmittag gibt es leichten Regen bei nur 16 Grad."',
          },
        ],
      },
    ],
  },
  {
    id: 'cert-test-a1-2',
    levelCode: 'a1-2',
    titleDe: 'For Great Nation A1.2 Assessment',
    titleUz: 'A1.2 Nemis Tili Baholash Imtihoni',
    descriptionUz: 'A1.2 kursi mavzulari (kasb-kor, salomatlik, shifokor qabuli, sayohat, uy-joy ijarasi va o‘tgan zamon Perfekt shakllari) bo‘yicha to‘liq o‘qish va tinglab tushunish imtihoni.',
    durationMinutes: 35,
    passingPercentage: 60,
    isPublished: true,
    totalPoints: 40,
    totalQuestions: 10,
    sections: [
      {
        id: 'sec-a1-2-lesen',
        testId: 'cert-test-a1-2',
        skill: 'reading',
        titleDe: 'Teil 1: Lesen (O‘qish va Tushunish)',
        titleUz: '1-Bo‘lim: O‘qib tushunish',
        instructionsUz: 'Har bir vaziyat va matnni diqqat bilan o‘rganib, eng to‘g‘ri javobni tanlang.',
        orderIndex: 1,
        questions: [
          {
            id: 'q-a1-2-r1',
            sectionId: 'sec-a1-2-lesen',
            orderIndex: 1,
            type: 'multiple_choice',
            promptDe: 'Warum schreibt Frau Krause an Herrn Berger?',
            promptUz: 'Krauze xonim nima sababdan Berger janoblariga xat yozmoqda?',
            passageDe: 'Sehr geehrter Herr Berger, vielen Dank für Ihre Einladung zum Vorstellungsgespräch am Dienstag. Leider muss ich den Termin absagen, da mein Sohn plötzlich krank geworden ist. Könnten wir das Gespräch auf Donnerstag um 10:00 Uhr verschieben? Mit freundlichen Grüßen, Sabine Krause.',
            options: [
              { id: 'opt-1', textDe: 'Sie möchte die Stelle nicht mehr annehmen.', textUz: 'U ishga kirishni xohlamaydi.' },
              { id: 'opt-2', textDe: 'Sie möchte den Termin verschieben, weil ihr Sohn krank ist.', textUz: 'O‘g‘li kasal bo‘lib qolgani sababli uchrashuv vaqtini ko‘chirmoqchi.' },
              { id: 'opt-3', textDe: 'Sie hat am Dienstag schon gearbeitet.', textUz: 'U seshanba kuni allaqachon ishlab bo‘lgan.' },
              { id: 'opt-4', textDe: 'Sie sucht eine neue Wohnung.', textUz: 'U yangi kvartira qidirmoqda.' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Xatda "Leider muss ich den Termin absagen, da mein Sohn plötzlich krank geworden ist. Könnten wir das Gespräch... verschieben?" deb yozilgan.',
          },
          {
            id: 'q-a1-2-r2',
            sectionId: 'sec-a1-2-lesen',
            orderIndex: 2,
            type: 'true_false',
            promptDe: 'Richtig oder Falsch: Haustiere sind in der Wohnung erlaubt.',
            promptUz: 'To‘g‘ri yoki Noto‘g‘ri: Ushbu kvartirada uy hayvonlarini boqishga ruxsat berilganmi?',
            passageDe: 'WOHNUNGSANZEIGE:\nHelle 3-Zimmer-Wohnung in Hamburg-Altona. 75 qm, mit Balkon und Einbauküche. Kaltmiete 850 Euro zzgl. 150 Euro Nebenkosten. Nichtraucher erwünscht. Wichtig: Keine Haustiere erlaubt! Frei ab 1. November.',
            options: [
              { id: 'opt-r', textDe: 'Richtig (Ruxsat berilgan)', textUz: 'Uy hayvonlari saqlash mumkin' },
              { id: 'opt-f', textDe: 'Falsch (Ruxsat berilmagan)', textUz: 'Uy hayvonlarini saqlash man etilgan' },
            ],
            correctAnswer: 'opt-f',
            points: 4,
            explanationUz: 'E‘londa: "Wichtig: Keine Haustiere erlaubt!" (Muhim: Uy hayvonlariga ruxsat berilmaydi!) deyilgan.',
          },
          {
            id: 'q-a1-2-r3',
            sectionId: 'sec-a1-2-lesen',
            orderIndex: 3,
            type: 'multiple_choice',
            promptDe: 'Wie oft soll Herr Meier die Tabletten einnehmen?',
            promptUz: 'Dori qabul qilish qoidasiga ko‘ra, tabletkalarni qachon va necha marta ichish kerak?',
            passageDe: 'PATIENTENINFORMATION:\nMedikament: Paracetamol 500mg.\nAnwendung: Bitte nehmen Sie dreimal täglich jeweils eine Tablette nach dem Essen mit viel Wasser ein. Die maximale Tagesdosis beträgt drei Tabletten.',
            options: [
              { id: 'opt-1', textDe: 'Einmal pro Woche', textUz: 'Haftada bir marta' },
              { id: 'opt-2', textDe: 'Dreimal täglich nach dem Essen', textUz: 'Kuniga 3 marta ovqatdan keyin' },
              { id: 'opt-3', textDe: 'Vor dem Schlafen zwei Tabletten', textUz: 'Uxlashdan oldin 2 ta tabletka' },
              { id: 'opt-4', textDe: 'Jede Stunde eine Tablette', textUz: 'Har soatda bittadan' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Ko‘rsatmada aniq belgilangan: "dreimal täglich jeweils eine Tablette nach dem Essen".',
          },
          {
            id: 'q-a1-2-r4',
            sectionId: 'sec-a1-2-lesen',
            orderIndex: 4,
            type: 'multiple_choice',
            promptDe: 'Was hat Florian am Wochenende gemacht?',
            promptUz: 'Florian dam olish kunlarida nima qildi?',
            passageDe: 'Lieber Max, mein Wochenende war super! Am Samstag bin ich mit dem Zug nach Köln gefahren. Dort habe ich den Kölner Dom besichtigt und abends haben wir mit Freunden gegrillt. Am Sonntag habe ich lange geschlafen und ein Buch gelesen.',
            options: [
              { id: 'opt-1', textDe: 'Er hat das ganze Wochenende gearbeitet.', textUz: 'U butun hafta oxiri ishlagan.' },
              { id: 'opt-2', textDe: 'Er ist nach Köln gefahren, hat den Dom besichtigt und gegrillt.', textUz: 'U Kyolnga borgan, cherkovni ko‘rgan va do‘stlari bilan kabob pishirgan.' },
              { id: 'opt-3', textDe: 'Er ist nach Berlin geflogen.', textUz: 'U Berlinga uchib ketgan.' },
              { id: 'opt-4', textDe: 'Er war krank im Bett.', textUz: 'U kasal bo‘lib yotgan.' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Matnda o‘tgan zamon (Perfekt) fe‘llari orqali: "nach Köln gefahren... Dom besichtigt... gegrillt" deb tasvirlangan.',
          },
          {
            id: 'q-a1-2-r5',
            sectionId: 'sec-a1-2-lesen',
            orderIndex: 5,
            type: 'multiple_choice',
            promptDe: 'Bis wann kann man sich für den Deutschkurs anmelden?',
            promptUz: 'Nemis tili kursiga oxirgi ro‘yxatdan o‘tish muddati qachongacha?',
            passageDe: 'SPRACHSCHULE LINGUA:\nIntensivkurs Deutsch A2. Beginn: 15. Oktober. Unterricht: Mo–Do 09:00–12:30 Uhr. Anmeldeschluss ist der 5. Oktober. Spätere Anmeldungen können leider nicht berücksichtigt werden.',
            options: [
              { id: 'opt-1', textDe: 'Bis zum 15. Oktober', textUz: '15-oktyabrgacha (kurs boshlanishi)' },
              { id: 'opt-2', textDe: 'Bis zum 5. Oktober', textUz: '5-oktyabrgacha (oxirgi muddat)' },
              { id: 'opt-3', textDe: 'Jederzeit online', textUz: 'Istalgan vaqtda' },
              { id: 'opt-4', textDe: 'Nur am Donnerstag', textUz: 'Faqat payshanba kuni' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'E‘londa aytilgan: "Anmeldeschluss ist der 5. Oktober" (Ro‘yxatdan o‘tishning so‘nggi kuni 5-oktyabr).',
          },
        ],
      },
      {
        id: 'sec-a1-2-hoeren',
        testId: 'cert-test-a1-2',
        skill: 'listening',
        titleDe: 'Teil 2: Hören (Tinglab Tushunish)',
        titleUz: '2-Bo‘lim: Tinglab tushunish',
        instructionsUz: 'Har bir audio vaziyatni tinglang va berilgan savollarga eng to‘g‘ri javobni tanlang.',
        orderIndex: 2,
        questions: [
          {
            id: 'q-a1-2-h1',
            sectionId: 'sec-a1-2-hoeren',
            orderIndex: 6,
            type: 'multiple_choice',
            promptDe: 'Wann hat Herr Braun den neuen Termin beim Arzt?',
            promptUz: 'Janob Braunning shifokor bilan yangi uchrashuvi qaysi kunga belgilandi?',
            audioText: 'Guten Tag, Herr Braun. Hier ist die Praxis Dr. Wagner. Sie hatten einen Termin für morgen früh um 9 Uhr. Dr. Wagner muss jedoch zu einer Operation. Wir können Ihnen einen Termin am Freitag um 11:30 Uhr anbieten. Bitte melden Sie sich kurz.',
            transcriptDe: 'Guten Tag, Herr Braun. Hier ist die Praxis Dr. Wagner. Sie hatten einen Termin für morgen früh um 9 Uhr. Dr. Wagner muss jedoch zu einer Operation. Wir können Ihnen einen Termin am Freitag um 11:30 Uhr anbieten. Bitte melden Sie sich kurz.',
            options: [
              { id: 'opt-1', textDe: 'Morgen um 9:00 Uhr', textUz: 'Ertaga soat 9:00 da' },
              { id: 'opt-2', textDe: 'Am Freitag um 11:30 Uhr', textUz: 'Juma kuni soat 11:30 da' },
              { id: 'opt-3', textDe: 'Am Donnerstag um 15:00 Uhr', textUz: 'Payshanba kuni soat 15:00 da' },
              { id: 'opt-4', textDe: 'Am Montag um 10:00 Uhr', textUz: 'Dushanba kuni soat 10:00 da' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Audioda taklif qilingan yangi vaqt: "am Freitag um 11:30 Uhr".',
          },
          {
            id: 'q-a1-2-h2',
            sectionId: 'sec-a1-2-hoeren',
            orderIndex: 7,
            type: 'true_false',
            promptDe: 'Richtig oder Falsch: Die U-Bahn Linie 2 fährt heute ganz normal bis zum Hauptbahnhof.',
            promptUz: 'To‘g‘ri yoki Noto‘g‘ri: U2 metro liniyasi bugun bosh bekatgacha odatiy tartibda qatnayaptimi?',
            audioText: 'Fahrgastinformation: Wegen Bauarbeiten fährt die U-Bahn-Linie U2 heute nur bis zum Rathausmarkt. Zwischen Rathausmarkt und Hauptbahnhof nutzen Sie bitte den Schienenersatzverkehr mit Bussen.',
            transcriptDe: 'Fahrgastinformation: Wegen Bauarbeiten fährt die U-Bahn-Linie U2 heute nur bis zum Rathausmarkt. Zwischen Rathausmarkt und Hauptbahnhof nutzen Sie bitte den Schienenersatzverkehr mit Bussen.',
            options: [
              { id: 'opt-r', textDe: 'Richtig (To‘g‘ri)', textUz: 'Poyezd bekatgacha to‘xtovsiz qatnamoqda' },
              { id: 'opt-f', textDe: 'Falsch (Noto‘g‘ri)', textUz: 'Ta‘mirlash sababli avtobuslarga o‘tish kerak' },
            ],
            correctAnswer: 'opt-f',
            points: 4,
            explanationUz: 'Metro xabarnomasida: "fährt heute nur bis zum Rathausmarkt... nutzen Sie bitte den Schienenersatzverkehr mit Bussen" deyilgan.',
          },
          {
            id: 'q-a1-2-h3',
            sectionId: 'sec-a1-2-hoeren',
            orderIndex: 8,
            type: 'multiple_choice',
            promptDe: 'Was soll Tim aus dem Supermarkt mitbringen?',
            promptUz: 'Tim do‘kondan nimalar sotib olib kelishi kerak?',
            audioText: 'Hallo Tim, ich bin noch im Büro. Kannst du bitte auf dem Heimweg einkaufen gehen? Wir brauchen noch Milch, ein Kilo Tomaten und eine Packung Kaffee. Brot haben wir noch. Danke, bis später!',
            transcriptDe: 'Hallo Tim, ich bin noch im Büro. Kannst du bitte auf dem Heimweg einkaufen gehen? Wir brauchen noch Milch, ein Kilo Tomaten und eine Packung Kaffee. Brot haben wir noch. Danke, bis später!',
            options: [
              { id: 'opt-1', textDe: 'Milch, Tomaten und Kaffee', textUz: 'Sut, pomidor va qahva' },
              { id: 'opt-2', textDe: 'Brot, Käse und Butter', textUz: 'Non, pishloq va sariyog‘' },
              { id: 'opt-3', textDe: 'Nur Brot und Milch', textUz: 'Faqat non va sut' },
              { id: 'opt-4', textDe: 'Apfelsaft und Fleisch', textUz: 'Olma sharbati va go‘sht' },
            ],
            correctAnswer: 'opt-1',
            points: 4,
            explanationUz: 'Ovozli xabarda aytilgan: "Wir brauchen noch Milch, ein Kilo Tomaten und eine Packung Kaffee. Brot haben wir noch."',
          },
          {
            id: 'q-a1-2-h4',
            sectionId: 'sec-a1-2-hoeren',
            orderIndex: 9,
            type: 'multiple_choice',
            promptDe: 'Was gefällt Julia an ihrer neuen Arbeit besonders gut?',
            promptUz: 'Yuliyaga o‘zining yangi ishida nima ko‘proq yoqadi?',
            audioText: 'Hi Claudia! Ja, ich habe vor zwei Wochen meine neue Stelle im Hotel angefangen. Das Gehalt ist in Ordnung, aber das Beste sind die Kollegen: Alle sind super nett und helfen mir sehr viel. Die Arbeitszeiten sind manchmal anstrengend, aber ich bin wirklich zufrieden.',
            transcriptDe: 'Hi Claudia! Ja, ich habe vor zwei Wochen meine neue Stelle im Hotel angefangen. Das Gehalt ist in Ordnung, aber das Beste sind die Kollegen: Alle sind super nett und helfen mir sehr viel. Die Arbeitszeiten sind manchmal anstrengend, aber ich bin wirklich zufrieden.',
            options: [
              { id: 'opt-1', textDe: 'Das sehr hohe Gehalt', textUz: 'Juda baland maosh' },
              { id: 'opt-2', textDe: 'Die sehr netten und hilfsbereiten Kollegen', textUz: 'Juda mehribon va yordamga shay hamkasblar' },
              { id: 'opt-3', textDe: 'Die kurzen Arbeitszeiten', textUz: 'Qisqa ish vaqti' },
              { id: 'opt-4', textDe: 'Das kostenlose Essen im Hotel', textUz: 'Mehmonxonadagi bepul ovqat' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Yuliya aytmoqda: "das Beste sind die Kollegen: Alle sind super nett und helfen mir sehr viel."',
          },
          {
            id: 'q-a1-2-h5',
            sectionId: 'sec-a1-2-hoeren',
            orderIndex: 10,
            type: 'multiple_choice',
            promptDe: 'Wohin fahren Jan und Sandra am Wochenende?',
            promptUz: 'Yan va Sandra dam olish kunlarida qayerga borishadi?',
            audioText: 'Sandra, was machen wir am Wochenende? Das Wetter soll ja herrlich werden! Wollen wir an die Ostsee fahren und am Strand spazieren gehen? Wir könnten uns Fahrräder mieten. Was denkst du? Klingt doch toll, oder?',
            transcriptDe: 'Sandra, was machen wir am Wochenende? Das Wetter soll ja herrlich werden! Wollen wir an die Ostsee fahren und am Strand spazieren gehen? Wir könnten uns Fahrräder mieten. Was denkst du? Klingt doch toll, oder?',
            options: [
              { id: 'opt-1', textDe: 'In die Berge zum Wandern', textUz: 'Tog‘larga piyoda sayrga' },
              { id: 'opt-2', textDe: 'An die Ostsee an den Strand', textUz: 'Boltiq dengizi (Ostsee) sohiliga' },
              { id: 'opt-3', textDe: 'In ein Museum nach Frankfurt', textUz: 'Frankfurtdagi muzeyga' },
              { id: 'opt-4', textDe: 'Sie bleiben zu Hause', textUz: 'Uyda qolishadi' },
            ],
            correctAnswer: 'opt-2',
            points: 4,
            explanationUz: 'Audioda Yan taklif qilmoqda: "Wollen wir an die Ostsee fahren und am Strand spazieren gehen?"',
          },
        ],
      },
    ],
  },
];
